### ISSUE TITLE
test variant/clarification

### ISSUE THREAD

**Issue by moeller0** [heistp/sce-l4s-bakeoff#1]
Excellent! Thank you all for doing all this testing to put things on a solid footing!

I do have a question about scenario5/6 that I could not figure out myself yet.

In the beginning it says:

"All bottlenecks restrict to 50Mbit, unless otherwise noted."

Does this mean that in the scenario 5 and 6 all of the the (L4S/SCE, the) FiFO and the FQ-AQM are set to exactly 50 Mbps? I would assume that to be wrong and the bottlenecks to be successively narrower, but I fail to see exactly where this is configured?

And does the FQ-AQM shape on the ingress or egress side (not that that should matter much)?

**Comment by chromi** [comment]
Each graph has a (rather terse) description of the path in the header.  From this you can deduce exactly which qdisc and how much bandwidth is present at each node.

The FQ-AQM in scenarios 5 & 6 is the last and narrowest bottleneck in the chain, downstream of a dumb FIFO.

 - Jonathan Morton

**Comment by heistp** [comment]
Made that explicit in the text for scenarios 5 and 6, should have been that way before.

All shaping occurs on egress except for netem delays, which occur on ingress. One could figure that out from the setup logs, but I included that in the bandwidth note to make that a little easier.

Thanks!
